title: Advent of Parsing 2022
description: How to parse the input files of the Advent of Code 2022
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# remote_theme: just-the-docs/just-the-docs

url: https://papibe.github.io/advent-of-parsing-2022/

aux_links:
  Template Repository: https://github.com/papibe/advent-of-parsing-2022
